name: CD

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      dry_run:
        description: "--dry-run"
        required: false
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}
      - uses: oven-sh/setup-bun@v2
      - run: bun i
      - run: bun run build
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
          registry-url: "https://registry.npmjs.org"
      - name: Publish
        run: |
          if [ "${{ github.event.inputs.dry_run || 'false' }}" = "false" ]; then
            npm publish --provenance
          else
            npm publish --provenance --dry-run
          fi
